# Generated by Django 3.2.5 on 2021-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
